#!/bin/bash

clear
cyan='\e[1;36m%s\e[0m\n'
green='\e[1;32m%s\e[0m\n'
printf "$cyan"
./.banner
printf "$green" "Note After using m4skup tool use this "
echo ""
read -p "Enter the full path with m4skup file name: " fl
read -p "Enter comany name: " comp
mkdir ~/recon/$comp
cd ~/recon/$comp/
mkdir w3bmint3r
cd w3bmint3r
while read line;do
 sudo masscan $line -p10000 >> w3bmint3r.txt
done < $fl 
